# Generated by Django 4.2.3 on 2023-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
